version: '2'

services:
  db:
      image: postgres
      environment:
        - POSTGRES_DB=exchange_matching
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=ece568
      volumes:
            - data-volume:/var/lib/postgre

  main:
      build: ./src
      # command: bash -c "make clean && make && ./src/main"
      volumes:
        - ./src:/var/log/erss
      depends_on:
        - db
      ports:
        - "12345:12345"
volumes:
   data-volume:
